dtb-$(CONFIG_ARCH_MSM8916) += msm8916-cdp.dtb \
       msm8916-cdp-smb1360.dtb \
       msm8916-mtp.dtb \
       msm8916-512mb-mtp.dtb \
       msm8916-mtp-smb1360.dtb \
       msm8916-512mb-mtp-smb1360.dtb \
       msm8916-512mb-qrd-skui.dtb \
       msm8916-qrd-skuh.dtb \
       msm8916-qrd-skuhf.dtb \
       msm8916-qrd-skui.dtb \
       msm8916-512mb-qrd-skuh.dtb \

dtb-$(CONFIG_ARCH_MSM8994) += msm8994-cdp.dtb \
	msm8994-mtp.dtb \
	msm8994-liquid.dtb \
	apq8094-mtp.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
