dts-dirs += amd
dts-dirs += apm
dts-dirs += arm
dts-dirs += cavium
dts-dirs += exynos
dts-dirs += freescale
dts-dirs += mediatek
dtb-$(CONFIG_ARCH_MSM8994) += msm8994-sim.dtb \
	msm8994-rumi.dtb \
	msm8994-cdp.dtb \
	msm8994-mtp.dtb \
	msm8994-liquid.dtb \
	apq8094-mtp.dtb

subdir-y	:= $(dts-dirs)
